### ISSUE TITLE
Can you please compile the kext for Mac OS X 10.11 El Capitan?

### ISSUE THREAD

**Issue by AndrewK2685** [i3roly/C-Media#2]
The kext showed error while trying to load on Mac OS X El Capitan and eventually did not load.
(for Asus Xonar Essence ST) Can you please compile a version for it and check?

Thank you for your excellent work

**Comment by i3roly** [comment]
You need to disable system integrity protection in recovery mode. Someone has reported success on monterey already so it's not due to driver target, which is set for 10.7                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Rogers network.                                                                                                                                                                                                                From: AndrewK2685Sent: Friday, 30 August 2024 1:53 AMTo: i3roly/C-MediaReply To: i3roly/C-MediaCc: SubscribedSubject: [i3roly/C-Media] Can you please compile the kext for Mac OS X 10.11 El Capitan? (Issue #2)
The kext showed error while trying to load on Mac OS X El Capitan and eventually did not load.
(for Asus Xonar Essence ST) Can you please compile a version for it and check?
Thank you for your excellent work

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/i3roly/C-Media/issues/2",
"url": "https://github.com/i3roly/C-Media/issues/2",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AndrewK2685** [comment]
Thank you for your response. Yes, I disabled SIP. This is what I'm getting (attached):

![20240830_221024](https://github.com/user-attachments/assets/4902d838-b002-494f-bf69-e74a38ee8268)

Bare in mind, I'm running an AMD Hackintoch with Shaneee kernel. Do you know if your kext uses SSE4.1?

**Comment by d3fa** [comment]
Try to use kext from previous [commit](https://github.com/i3roly/C-Media/tree/26d28f9c70cd51e08bb84287bd3400dc0a9a65d3)
current version doesn't work for me, 'small update' was broke the driver🤭
PS. update your crappy oldest El Capitan. This kext works fine even on macos Sequoia (old commit)

**Comment by i3roly** [comment]
> Try to use kext from previous [commit](https://github.com/i3roly/C-Media/tree/26d28f9c70cd51e08bb84287bd3400dc0a9a65d3)
> 
> current version doesn't work for me, 'small update' was broke the driver🤭
> 
> PS. update your crappy oldest El Capitan. This kext works fine even on macos Sequoia (old commit)

Thanks for information @d3fa  can you give me info on failed load for newer driver? All I changed was how IOLog macro behaviour worked. Symbols should be the same. 

Try kextload -v6 with failed kext and share any failure if you can?

**Comment by i3roly** [comment]
that's a weird error, thanks for sharing that.

considering all OS X should have strlcpy, i'm rather surprised that some _chk function is invoked.

i've attached a version that doesn't have this symbol. 

[PCIAudioDriver.kext.zip](https://github.com/user-attachments/files/16825527/PCIAudioDriver.kext.zip)

**Comment by AndrewK2685** [comment]
Thanks i3roly

Now I'm getting a different error, but similar concerning strncpy:

Mac-Pro-toutes-Andreas:~ AndrewK2685$ sudo kextutil /System/Library/Extensions/PCIAudioDriver.kext 
Password:
Diagnostics for /System/Library/Extensions/PCIAudioDriver.kext:
Code Signing Failure: code signature is invalid
kext-dev-mode allowing invalid signature -2147409622 0xFFFFFFFF8001212A for kext "/System/Library/Extensions/PCIAudioDriver.kext"
kext signature failure override allowing invalid signature -2147409622 0xFFFFFFFF8001212A for kext "/System/Library/Extensions/PCIAudioDriver.kext"
(kernel) kxld[com.CMedia.CMI8788.PCIAudioDriver]: The following symbols are unresolved for this kext:
(kernel) kxld[com.CMedia.CMI8788.PCIAudioDriver]: 	___strncpy_chk
(kernel) Can't load kext com.CMedia.CMI8788.PCIAudioDriver - link failed.
(kernel) Failed to load executable for kext com.CMedia.CMI8788.PCIAudioDriver.
(kernel) Kext com.CMedia.CMI8788.PCIAudioDriver failed to load (0xdc008016).
(kernel) Failed to load kext com.CMedia.CMI8788.PCIAudioDriver (error 0xdc008016).
Failed to load /System/Library/Extensions/PCIAudioDriver.kext - (libkern/kext) link error.
Check library declarations for your kext with kextlibs(8).
Mac-Pro-toutes-Andreas:~ AndrewK2685$ 

Is it any better?

**Comment by i3roly** [comment]
this one should work. looks like manually pointing to a specific version of macos in the xcode tools will inject these checks.

[PCIAudioDriver.kext.zip](https://github.com/user-attachments/files/16825639/PCIAudioDriver.kext.zip)

**Comment by AndrewK2685** [comment]
Hi i3roly

Thanks for your response.
The last one you attached is indeed loading witout errors, sets several properties and I can hear the relay of Xonar turning on 👍  .
Unfortunately, sortly after that the system crashes.. :

![20240901_102714](https://github.com/user-attachments/assets/ff79d458-48db-485f-bb57-da7857bfd001)

I think this might be related to the overall audio framework. Any ideas?

**Comment by i3roly** [comment]
sounds like an issue with the pci memory mask. you can try the latest build that i just posted on the main and see if it helps.

otherwise i can't really help you because no x86 mac desktop ever shipped with PCI. the earliest x86 desktop mac that came with expansion slots was the 08 mac pro, which supported PCI-E only.

if the pci address bus mask doesn't fix the issue, then i have no idea. it's not the audio engine.

**Comment by i3roly** [comment]
did that fix the problem or not? any more information? if it's the same error it may be an incompatibility with the PCI driver and your board.

have you looked into this at all? i think the only PCI support was from the power pc era?? i can't even remember hackintosh being a thing prior to the release of x58 stuff

**Comment by AndrewK2685** [comment]
Hi
Sorry for my late response.
Yes unfortunately its crashing again, probably because of PCI incompatibility as you said.
Unfortunately I don't have a PCIe version of the card to test, but other than that the kext
seems to be ready, without the loading issues that it had before.
If someone with an Asus Xonar Essence STX (or another PCIe version) could test it and report
back that would be great. I'm also considering trying it with a version of the PCI era
(e.g. Leopard) but that would take some time. If manage to do it I will post the resullts here :) .
Nevertheless, thank you for all your effords it was great to see that such great hardware find
their way into macOS 👍. Hope that more soundcards will follow :).

**Comment by i3roly** [comment]
i have an stx 2 and that’s why i’m telling you it works. the stx 2 is the pci-e version of the stx.

but the error was strange. you should ask hackintosh people to be sure and get back to me.

this won’t work on PPC machines because i haven’t backported any of the code since i don’t have one of those machines.

**Comment by i3roly** [comment]
and which kext did you use? the one i uploaded on the main page (not in comments)? can you give me a picture of the error next time so i can see it?

**Comment by AndrewK2685** [comment]
AAAHHAAAAA

I'm getting a weird situation here.
As I told you the last version of the kext crashed like the previous one. So today I went to grab a pic from the crash and got this
![20240903_190524](https://github.com/user-attachments/assets/137a2451-b7b5-4f4a-ac13-bb08db6f8017)

Seems like coreaudiod service was involved
I tried to repeat the crash to see if I could get the backtrace of the kexts involved. So pressed reset and waited.
This time however.... the system booted!!! 
Not only that, it registered the card as PCI Audio device and I could get sound out of it !!!!! :D :D :D

![20240903_200506](https://github.com/user-attachments/assets/abb52df5-8129-438f-8f8b-fbabae7c9a55)
![20240903_200645](https://github.com/user-attachments/assets/07f0480c-24c3-4782-9fc9-4f75c0e1735f)
After a reset it crashed again. But after anotherone it booted correctly again!!!
As such, I'm 100% sure your kext is working - Thank you for your time, effords and support!! you did it!!
-I blame the patched AMD kernel for the instabilities, which also gives me a lot of other problems as welll...
but its something I can live with :D

**Comment by i3roly** [comment]
hahahaha i’m glad you’re happy.

it’s pretty awesome having this card in mac os x.

enjoy buddy. report on additional functionality if there are problems (i.e. spdif out) but it should be fine.

if i had more people with real skills (no offence to you), i would have worked on setting up good defaults for the midi setup, but i don’t.

nonetheless please report anything you notice if you think it will help the user experience.

**Comment by AndrewK2685** [comment]
Thanks a lot. Will definetely do if something else comes up 👍
